#!/usr/bin/env bash

set -euo pipefail

[[ $# -eq 0 ]] && exit
strace -etrace=execve -f --string-limit $((10 ** 6)) -qq --output strace.$PPID.out "${@}" || true
node "$(dirname "$(realpath "$0")")/filter-exec.js" < strace.$PPID.out
rm strace.$PPID.out
